spring:
  application:
    name: KittyBookStoreService
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/kittybookstoredb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always  # 启动时总是执行 schema.sql
      platform: mysql
mybatis:
  mapper-locations: classpath*:mapper/*.xml   # Mapper XML 存放路径
  type-aliases-package: com.book.store.entity # 实体类包路径
  configuration:
    map-underscore-to-camel-case: true  # 数据库下划线字段自动映射到Java驼峰命名